// get product data
export const LOAD_PRODUCT_DATA_START="LOAD_PRODUCT_DATA_START"
export const LOAD_PRODUCT_DATA_SUCCESS="LOAD_PRODUCT_DATA_SUCCESS"
export const LOAD_PRODUCT_DATA_ERROR="LOAD_PRODUCT_DATA_ERROR"